<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JTAuth.Application\JTAuth.Application.csproj" />
  </ItemGroup>

</Project>
